# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prilogenie111', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='city_name',
            new_name='country_name',
        ),
        migrations.RenameField(
            model_name='town',
            old_name='city',
            new_name='country',
        ),
    ]
